SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'seqListingID', N'SO') IS NULL
BEGIN

    CREATE SEQUENCE [dbo].[seqListingID] AS [int]
        START WITH 25000001
        INCREMENT BY 1
        MINVALUE 25000001
        MAXVALUE 99999999
        CACHE 10

END
GO