SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'seqLotteryID', N'SO') IS NULL
BEGIN

    CREATE SEQUENCE [dbo].[seqLotteryID] AS [int]
        START WITH 25000101
        INCREMENT BY 1
        MINVALUE 25000101
        MAXVALUE 9999999
        CACHE 10

END
GO