using System;
using System.Diagnostics.CodeAnalysis;

namespace WHLAdmin.Common.Models;

[ExcludeFromCodeCoverage]
public class HousingApplicationDownload
{
    public int LotteryNumber { get; set; }
    public int LotteryID { get; set; }
    public int ApplicationID { get; set; }
    public string SubmissionTypeCD { get; set; }
    public DateTime SubmittedDate { get; set; }
    public string StatusCD { get; set; }
    public string Username { get; set; }
    public string UnitTypeCDs { get; set; }
    public string AccessibilityCDs { get; set; }
    public string LeadTypeCD { get; set; }
    public string LeadTypeOther { get; set; }
    public string ApplicantTitle { get; set; }
    public string ApplicantFirstName { get; set; }
    public string ApplicantMiddleName { get; set; }
    public string ApplicantLastName { get; set; }
    public string ApplicantSuffix { get; set; }
    public DateTime ApplicantDateOfBirth { get; set; }
    public string ApplicantLast4SSN { get; set; }
    public string ApplicantIDTypeCD { get; set; }
    public string ApplicantIDTypeValue { get; set; }
    public DateTime ApplicantIDIssueDate { get; set; }
    public string ApplicantGenderCD { get; set; }
    public string ApplicantRaceCD { get; set; }
    public string ApplicantEthnicityCD { get; set; }
    public string ApplicantPronouns { get; set; }
    public bool ApplicantStudentInd { get; set; }
    public bool ApplicantDisabilityInd { get; set; }
    public bool ApplicantVeteranInd { get; set; }
    public bool ApplicantEverLivedInWestchesterInd { get; set; }
    public string ApplicantCountyLivingIn { get; set; }
    public string ApplicantCountyWorkingIn { get; set; }
    public string ApplicantPhoneNumber { get; set; }
    public string ApplicantPhoneNumberExtn { get; set; }
    public string ApplicantPhoneNumberTypeCD { get; set; }
    public string ApplicantAltPhoneNumber { get; set; }
    public string ApplicantAltPhoneNumberExtn { get; set; }
    public string ApplicantAltPhoneNumberTypeCD { get; set; }
    public string ApplicantEmailAddress { get; set; }
    public string ApplicantAltEmailAddress { get; set; }
    public string PhysicalStreetLine1 { get; set; }
    public string PhysicalStreetLine2 { get; set; }
    public string PhysicalStreetLine3 { get; set; }
    public string PhysicalCity { get; set; }
    public string PhysicalStateCD { get; set; }
    public string PhysicalZipCode { get; set; }
    public string PhysicalCounty { get; set; }
    public string MailingStreetLine1 { get; set; }
    public string MailingStreetLine2 { get; set; }
    public string MailingStreetLine3 { get; set; }
    public string MailingCity { get; set; }
    public string MailingStateCD { get; set; }
    public string MailingZipCode { get; set; }
    public string MailingCounty { get; set; }
    public string CoApplicantTitle { get; set; }
    public string CoApplicantFirstName { get; set; }
    public string CoApplicantMiddleName { get; set; }
    public string CoApplicantLastName { get; set; }
    public string CoApplicantSuffix { get; set; }
    public DateTime CoApplicantDateOfBirth { get; set; }
    public string CoApplicantLast4SSN { get; set; }
    public string CoApplicantIDTypeCD { get; set; }
    public string CoApplicantIDTypeValue { get; set; }
    public DateTime CoApplicantIDIssueDate { get; set; }
    public string CoApplicantGenderCD { get; set; }
    public string CoApplicantRaceCD { get; set; }
    public string CoApplicantEthnicityCD { get; set; }
    public string CoApplicantPronouns { get; set; }
    public bool CoApplicantStudentInd { get; set; }
    public bool CoApplicantDisabilityInd { get; set; }
    public bool CoApplicantVeteranInd { get; set; }
    public bool CoApplicantEverLivedInWestchesterInd { get; set; }
    public string CoApplicantCountyLivingIn { get; set; }
    public string CoApplicantCountyWorkingIn { get; set; }
    public string CoApplicantPhoneNumber { get; set; }
    public string CoApplicantPhoneNumberExtn { get; set; }
    public string CoApplicantPhoneNumberTypeCD { get; set; }
    public string CoApplicantAltPhoneNumber { get; set; }
    public string CoApplicantAltPhoneNumberExtn { get; set; }
    public string CoApplicantAltPhoneNumberTypeCD { get; set; }
    public string CoApplicantEmailAddress { get; set; }
    public string CoApplicantAltEmailAddress { get; set; }
    public string Member1Title { get; set; }
    public string Member1FirstName { get; set; }
    public string Member1MiddleName { get; set; }
    public string Member1LastName { get; set; }
    public string Member1Suffix { get; set; }
    public DateTime Member1DateOfBirth { get; set; }
    public string Member1Last4SSN { get; set; }
    public string Member1IDTypeCD { get; set; }
    public string Member1IDTypeValue { get; set; }
    public DateTime Member1IDIssueDate { get; set; }
    public string Member1GenderCD { get; set; }
    public string Member1RaceCD { get; set; }
    public string Member1EthnicityCD { get; set; }
    public string Member1Pronouns { get; set; }
    public bool Member1StudentInd { get; set; }
    public bool Member1DisabilityInd { get; set; }
    public bool Member1VeteranInd { get; set; }
    public bool Member1EverLivedInWestchesterInd { get; set; }
    public string Member1CountyLivingIn { get; set; }
    public string Member1CountyWorkingIn { get; set; }
    public string Member1PhoneNumber { get; set; }
    public string Member1PhoneNumberExtn { get; set; }
    public string Member1PhoneNumberTypeCD { get; set; }
    public string Member1AltPhoneNumber { get; set; }
    public string Member1AltPhoneNumberExtn { get; set; }
    public string Member1AltPhoneNumberTypeCD { get; set; }
    public string Member1EmailAddress { get; set; }
    public string Member1AltEmailAddress { get; set; }
    public string Member2Title { get; set; }
    public string Member2FirstName { get; set; }
    public string Member2MiddleName { get; set; }
    public string Member2LastName { get; set; }
    public string Member2Suffix { get; set; }
    public DateTime Member2DateOfBirth { get; set; }
    public string Member2Last4SSN { get; set; }
    public string Member2IDTypeCD { get; set; }
    public string Member2IDTypeValue { get; set; }
    public DateTime Member2IDIssueDate { get; set; }
    public string Member2GenderCD { get; set; }
    public string Member2RaceCD { get; set; }
    public string Member2EthnicityCD { get; set; }
    public string Member2Pronouns { get; set; }
    public bool Member2StudentInd { get; set; }
    public bool Member2DisabilityInd { get; set; }
    public bool Member2VeteranInd { get; set; }
    public bool Member2EverLivedInWestchesterInd { get; set; }
    public string Member2CountyLivingIn { get; set; }
    public string Member2CountyWorkingIn { get; set; }
    public string Member2PhoneNumber { get; set; }
    public string Member2PhoneNumberExtn { get; set; }
    public string Member2PhoneNumberTypeCD { get; set; }
    public string Member2AltPhoneNumber { get; set; }
    public string Member2AltPhoneNumberExtn { get; set; }
    public string Member2AltPhoneNumberTypeCD { get; set; }
    public string Member2EmailAddress { get; set; }
    public string Member2AltEmailAddress { get; set; }
    public string Member3Title { get; set; }
    public string Member3FirstName { get; set; }
    public string Member3MiddleName { get; set; }
    public string Member3LastName { get; set; }
    public string Member3Suffix { get; set; }
    public DateTime Member3DateOfBirth { get; set; }
    public string Member3Last4SSN { get; set; }
    public string Member3IDTypeCD { get; set; }
    public string Member3IDTypeValue { get; set; }
    public DateTime Member3IDIssueDate { get; set; }
    public string Member3GenderCD { get; set; }
    public string Member3RaceCD { get; set; }
    public string Member3EthnicityCD { get; set; }
    public string Member3Pronouns { get; set; }
    public bool Member3StudentInd { get; set; }
    public bool Member3DisabilityInd { get; set; }
    public bool Member3VeteranInd { get; set; }
    public bool Member3EverLivedInWestchesterInd { get; set; }
    public string Member3CountyLivingIn { get; set; }
    public string Member3CountyWorkingIn { get; set; }
    public string Member3PhoneNumber { get; set; }
    public string Member3PhoneNumberExtn { get; set; }
    public string Member3PhoneNumberTypeCD { get; set; }
    public string Member3AltPhoneNumber { get; set; }
    public string Member3AltPhoneNumberExtn { get; set; }
    public string Member3AltPhoneNumberTypeCD { get; set; }
    public string Member3EmailAddress { get; set; }
    public string Member3AltEmailAddress { get; set; }
    public string Member4Title { get; set; }
    public string Member4FirstName { get; set; }
    public string Member4MiddleName { get; set; }
    public string Member4LastName { get; set; }
    public string Member4Suffix { get; set; }
    public DateTime Member4DateOfBirth { get; set; }
    public string Member4Last4SSN { get; set; }
    public string Member4IDTypeCD { get; set; }
    public string Member4IDTypeValue { get; set; }
    public DateTime Member4IDIssueDate { get; set; }
    public string Member4GenderCD { get; set; }
    public string Member4RaceCD { get; set; }
    public string Member4EthnicityCD { get; set; }
    public string Member4Pronouns { get; set; }
    public bool Member4StudentInd { get; set; }
    public bool Member4DisabilityInd { get; set; }
    public bool Member4VeteranInd { get; set; }
    public bool Member4EverLivedInWestchesterInd { get; set; }
    public string Member4CountyLivingIn { get; set; }
    public string Member4CountyWorkingIn { get; set; }
    public string Member4PhoneNumber { get; set; }
    public string Member4PhoneNumberExtn { get; set; }
    public string Member4PhoneNumberTypeCD { get; set; }
    public string Member4AltPhoneNumber { get; set; }
    public string Member4AltPhoneNumberExtn { get; set; }
    public string Member4AltPhoneNumberTypeCD { get; set; }
    public string Member4EmailAddress { get; set; }
    public string Member4AltEmailAddress { get; set; }
    public string Member5Title { get; set; }
    public string Member5FirstName { get; set; }
    public string Member5MiddleName { get; set; }
    public string Member5LastName { get; set; }
    public string Member5Suffix { get; set; }
    public DateTime Member5DateOfBirth { get; set; }
    public string Member5Last4SSN { get; set; }
    public string Member5IDTypeCD { get; set; }
    public string Member5IDTypeValue { get; set; }
    public DateTime Member5IDIssueDate { get; set; }
    public string Member5GenderCD { get; set; }
    public string Member5RaceCD { get; set; }
    public string Member5EthnicityCD { get; set; }
    public string Member5Pronouns { get; set; }
    public bool Member5StudentInd { get; set; }
    public bool Member5DisabilityInd { get; set; }
    public bool Member5VeteranInd { get; set; }
    public bool Member5EverLivedInWestchesterInd { get; set; }
    public string Member5CountyLivingIn { get; set; }
    public string Member5CountyWorkingIn { get; set; }
    public string Member5PhoneNumber { get; set; }
    public string Member5PhoneNumberExtn { get; set; }
    public string Member5PhoneNumberTypeCD { get; set; }
    public string Member5AltPhoneNumber { get; set; }
    public string Member5AltPhoneNumberExtn { get; set; }
    public string Member5AltPhoneNumberTypeCD { get; set; }
    public string Member5EmailAddress { get; set; }
    public string Member5AltEmailAddress { get; set; }
    public string Member6Title { get; set; }
    public string Member6FirstName { get; set; }
    public string Member6MiddleName { get; set; }
    public string Member6LastName { get; set; }
    public string Member6Suffix { get; set; }
    public DateTime Member6DateOfBirth { get; set; }
    public string Member6Last4SSN { get; set; }
    public string Member6IDTypeCD { get; set; }
    public string Member6IDTypeValue { get; set; }
    public DateTime Member6IDIssueDate { get; set; }
    public string Member6GenderCD { get; set; }
    public string Member6RaceCD { get; set; }
    public string Member6EthnicityCD { get; set; }
    public string Member6Pronouns { get; set; }
    public bool Member6StudentInd { get; set; }
    public bool Member6DisabilityInd { get; set; }
    public bool Member6VeteranInd { get; set; }
    public bool Member6EverLivedInWestchesterInd { get; set; }
    public string Member6CountyLivingIn { get; set; }
    public string Member6CountyWorkingIn { get; set; }
    public string Member6PhoneNumber { get; set; }
    public string Member6PhoneNumberExtn { get; set; }
    public string Member6PhoneNumberTypeCD { get; set; }
    public string Member6AltPhoneNumber { get; set; }
    public string Member6AltPhoneNumberExtn { get; set; }
    public string Member6AltPhoneNumberTypeCD { get; set; }
    public string Member6EmailAddress { get; set; }
    public string Member6AltEmailAddress { get; set; }
    public string Member7Title { get; set; }
    public string Member7FirstName { get; set; }
    public string Member7MiddleName { get; set; }
    public string Member7LastName { get; set; }
    public string Member7Suffix { get; set; }
    public DateTime Member7DateOfBirth { get; set; }
    public string Member7Last4SSN { get; set; }
    public string Member7IDTypeCD { get; set; }
    public string Member7IDTypeValue { get; set; }
    public DateTime Member7IDIssueDate { get; set; }
    public string Member7GenderCD { get; set; }
    public string Member7RaceCD { get; set; }
    public string Member7EthnicityCD { get; set; }
    public string Member7Pronouns { get; set; }
    public bool Member7StudentInd { get; set; }
    public bool Member7DisabilityInd { get; set; }
    public bool Member7VeteranInd { get; set; }
    public bool Member7EverLivedInWestchesterInd { get; set; }
    public string Member7CountyLivingIn { get; set; }
    public string Member7CountyWorkingIn { get; set; }
    public string Member7PhoneNumber { get; set; }
    public string Member7PhoneNumberExtn { get; set; }
    public string Member7PhoneNumberTypeCD { get; set; }
    public string Member7AltPhoneNumber { get; set; }
    public string Member7AltPhoneNumberExtn { get; set; }
    public string Member7AltPhoneNumberTypeCD { get; set; }
    public string Member7EmailAddress { get; set; }
    public string Member7AltEmailAddress { get; set; }
    public string Member8Title { get; set; }
    public string Member8FirstName { get; set; }
    public string Member8MiddleName { get; set; }
    public string Member8LastName { get; set; }
    public string Member8Suffix { get; set; }
    public DateTime Member8DateOfBirth { get; set; }
    public string Member8Last4SSN { get; set; }
    public string Member8IDTypeCD { get; set; }
    public string Member8IDTypeValue { get; set; }
    public DateTime Member8IDIssueDate { get; set; }
    public string Member8GenderCD { get; set; }
    public string Member8RaceCD { get; set; }
    public string Member8EthnicityCD { get; set; }
    public string Member8Pronouns { get; set; }
    public bool Member8StudentInd { get; set; }
    public bool Member8DisabilityInd { get; set; }
    public bool Member8VeteranInd { get; set; }
    public bool Member8EverLivedInWestchesterInd { get; set; }
    public string Member8CountyLivingIn { get; set; }
    public string Member8CountyWorkingIn { get; set; }
    public string Member8PhoneNumber { get; set; }
    public string Member8PhoneNumberExtn { get; set; }
    public string Member8PhoneNumberTypeCD { get; set; }
    public string Member8AltPhoneNumber { get; set; }
    public string Member8AltPhoneNumberExtn { get; set; }
    public string Member8AltPhoneNumberTypeCD { get; set; }
    public string Member8EmailAddress { get; set; }
    public string Member8AltEmailAddress { get; set; }
    public string Member9Title { get; set; }
    public string Member9FirstName { get; set; }
    public string Member9MiddleName { get; set; }
    public string Member9LastName { get; set; }
    public string Member9Suffix { get; set; }
    public DateTime Member9DateOfBirth { get; set; }
    public string Member9Last4SSN { get; set; }
    public string Member9IDTypeCD { get; set; }
    public string Member9IDTypeValue { get; set; }
    public DateTime Member9IDIssueDate { get; set; }
    public string Member9GenderCD { get; set; }
    public string Member9RaceCD { get; set; }
    public string Member9EthnicityCD { get; set; }
    public string Member9Pronouns { get; set; }
    public bool Member9StudentInd { get; set; }
    public bool Member9DisabilityInd { get; set; }
    public bool Member9VeteranInd { get; set; }
    public bool Member9EverLivedInWestchesterInd { get; set; }
    public string Member9CountyLivingIn { get; set; }
    public string Member9CountyWorkingIn { get; set; }
    public string Member9PhoneNumber { get; set; }
    public string Member9PhoneNumberExtn { get; set; }
    public string Member9PhoneNumberTypeCD { get; set; }
    public string Member9AltPhoneNumber { get; set; }
    public string Member9AltPhoneNumberExtn { get; set; }
    public string Member9AltPhoneNumberTypeCD { get; set; }
    public string Member9EmailAddress { get; set; }
    public string Member9AltEmailAddress { get; set; }
    public string Member10Title { get; set; }
    public string Member10FirstName { get; set; }
    public string Member10MiddleName { get; set; }
    public string Member10LastName { get; set; }
    public string Member10Suffix { get; set; }
    public DateTime Member10DateOfBirth { get; set; }
    public string Member10Last4SSN { get; set; }
    public string Member10IDTypeCD { get; set; }
    public string Member10IDTypeValue { get; set; }
    public DateTime Member10IDIssueDate { get; set; }
    public string Member10GenderCD { get; set; }
    public string Member10RaceCD { get; set; }
    public string Member10EthnicityCD { get; set; }
    public string Member10Pronouns { get; set; }
    public bool Member10StudentInd { get; set; }
    public bool Member10DisabilityInd { get; set; }
    public bool Member10VeteranInd { get; set; }
    public bool Member10EverLivedInWestchesterInd { get; set; }
    public string Member10CountyLivingIn { get; set; }
    public string Member10CountyWorkingIn { get; set; }
    public string Member10PhoneNumber { get; set; }
    public string Member10PhoneNumberExtn { get; set; }
    public string Member10PhoneNumberTypeCD { get; set; }
    public string Member10AltPhoneNumber { get; set; }
    public string Member10AltPhoneNumberExtn { get; set; }
    public string Member10AltPhoneNumberTypeCD { get; set; }
    public string Member10EmailAddress { get; set; }
    public string Member10AltEmailAddress { get; set; }
}